--
--  File Name:         OsvvmTestCommonPkg_default.vhd
--  Design Unit Name:  OsvvmTestCommonPkg
--  Revision:          STANDARD VERSION
--
--  Maintainer:        Jim Lewis      email:  jim@synthworks.com
--
--  Description:
--     Default values for OsvvmTestCommonPkg for flows that do 
--     not use OSVVM scripting 
--
--
--  Developed for:
--        SynthWorks Design Inc.
--        VHDL Training Classes
--        11898 SW 128th Ave.  Tigard, Or  97223
--        http://www.SynthWorks.com
--
--  Revision History:
--    Version    Description
--    2026.05    Initial
--
--  This file is part of OSVVM.
--
--  Copyright (c) 2026 by SynthWorks Design Inc.
--
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
--
--      https://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.
--
-- This file is autogenerated by CreateTestCaseCommonPkg
library osvvm ;
context osvvm.OsvvmContext ;
package OsvvmTestCommonPkg is
  constant PATH_TO_TEST_SRC            : string  := "";
  constant PATH_TO_VALIDATED_RESULTS   : string  := "" ;
  constant CHECK_TRANSCRIPT            : boolean := FALSE ;  -- do not do any checking

  -- PATH_TO_RESULTS is for test case generated output other than TranscriptOpen.  If used you must create it
  constant BUILD_NAME                  : string  := "" ;
  constant TEST_SUITE_NAME             : string  := "" ;
  constant PATH_TO_RESULTS             : string  := "" ;

  -- Deprecated.  Provided for backward compatibility
  constant RESULTS_DIR             : string := PATH_TO_RESULTS ;
  constant VALIDATED_RESULTS_DIR   : string := PATH_TO_VALIDATED_RESULTS ;
end package OsvvmTestCommonPkg ;
